capture qui include "Code/0_settings.do"
capture qui include "0_settings.do" // When opening the slave from Windows Explorer, this will re-set cd to the project directory.
STOP // Activate this when working on the do-file, to avoid accidentally running the do-file from the top.
capture log close
log using "Code/Log/`0'.log", replace


/*
This do-file replicates the difference-in-differences (did) 
analysis with job postings/ads for the "canaries" paper.

Canaries repo downloaded on 2026-03-10.


INPUTS:


OUTPUTS:


*/



****************************************************************************************************
**# CHECK DATA SETS ********************************************************************************
****************************************************************************************************

**## INSPECT SOME DATASETS *************************************************************************

*Telework variable
import delimited "${data_raw}\Test 20260309\telework_ssyk_mapping.csv", clear



*Occupation-level dataset with exposure info:
import delimited "Replication 2026-03-10\canaries-sweden\data\processed\daioe_quartiles.csv", clear
	*One obs per occupation:
	duplicates report ssyk4
	sum pctl_rank_genai if high_exposure==1 // >0.75, as it should be. =1 for 106 obs (occupations).
	tab exposure_quartile
	tab exposure_quartile if high_exposure==1
	*Looks good.
	*--->>> TRY MERGING WITH MY EXPOSURE DATA.


*Postings data merged with exposure data:
import delimited "Replication 2026-03-10\canaries-sweden\data\processed\postings_daioe_merged.csv", clear



*Main did panel	dataset:
*(same as the previous one, postings_daioe_merged, but with additional variables needed for the did)
import delimited "Replication 2026-03-10\canaries-sweden\data\processed\did_panel.csv", clear



*csv with the main did result (specification 2):
import delimited "Replication 2026-03-10\canaries-sweden\tables\did_results_spec2.csv", clear
	list


**# COMPARE OLD AND NEW POSTINGS/ADS DATA BY MONTH *************************************************

/* Here we compare the new ads dataset with an old one generate independently by Erik last fall. */

*** IMPORT DATA ***
/*
*Erik
use "C:\Users\\`c(username)'\OneDrive - Ratio\Doktorandstudier\Forskning\P24_JMP\Data\3_data_jewelry\ssyk2012_4_month.dta", clear
	save "${data_raw}/ssyk2012_4_month_erik_original.dta", replace

*Claude
import delimited "Replication 2026-03-10\canaries-sweden\data\processed\postings_ssyk4_monthly.csv", clear
	save "${data_raw}/postings_ssyk4_monthly_claude_original.dta", replace
*/	


*** HARMONIZE THE TWO DATASETS ***

*(same variable names and formats, years observed)

*Claude
use "${data_raw}/postings_ssyk4_monthly_claude_original.dta", clear
	gen year = substr(year_month,1,4)
	destring year, replace
	keep if year>=2020 & year<=2024
	rename n_ads ads_claude
	count // 23367
	save "${data_raw}/postings_ssyk4_monthly_claude.dta", replace

*Erik
use "${data_raw}/ssyk2012_4_month_erik_original.dta", clear	
	keep if year>=2020 & year<=2024
	tostring year, gen(year_str)
	tostring month, gen(month_str)
	replace month_str = "0" + month_str if month<=9 & month>=1
	gen year_month = year_str + "-" + month_str
	gen ssyk4 = ssyk2012_4
	rename ads ads_erik
	count // 23425
	save "${data_raw}/ssyk2012_4_month_erik.dta", replace
	

	
*** MERGE AND COMPARE ***

*Open Claude data	
use "${data_raw}/postings_ssyk4_monthly_claude.dta", clear	
	*Merge with Erik data
	merge 1:1 year_month ssyk4 using "${data_raw}/ssyk2012_4_month_erik.dta", ///
		keepusing(ads_erik)
		*59 obs that are observed in my data but not Claude's. Inspect:
		br if _merge==2 // ~10 of these have missing SSYK.
		*A single obs in Claude data but not Erik data:
		br if _merge==1 // ssyk 3352, 2023-12.
		
	*Compare
	reg  ads_claude ads_erik
	corr ads_claude ads_erik
	


	
****************************************************************************************************	
**# REPLICATE MAIN DID RESULT **********************************************************************
****************************************************************************************************

/*
Specification to replicate (copied from Claude script):

ln(postings_it) = α_i + γ_t + β₁·PostRB_t·HighExp_i
						  + β₂·PostChatGPT_t·HighExp_i + ε_it

where:
  - i = SSYK4 occupation, t = year-month
  - α_i = occupation fixed effects
  - γ_t = time fixed effects (year-month dummies)
  - PostRB_t = 1 if t ≥ April 2022 (Riksbanken first hike)
  - PostChatGPT_t = 1 if t ≥ December 2022
  - HighExp_i = 1 if occupation in Q4 of genAI exposure

*/

**## USING DATASET GENERATED BY PIPELINE ***********************************************************

import delimited "Replication 2026-03-10\canaries-sweden\data\processed\did_panel.csv", clear
	
	*** RUN THE REGRESSION ***
	reghdfe ln_ads post_rb_x_high post_gpt_x_high, ///
		abs(ssyk4 year_month) vce(cluster ssyk4)
		
	*** 2020-2024 ONLY ***
	gen year = substr(year_month,1,4)
	destring year, replace
	tab year
	reghdfe ln_ads post_rb_x_high post_gpt_x_high if year>=2020 & year<=2024, ///
		abs(ssyk4 year_month) vce(cluster ssyk4)

		
		
	
**## USING MY DATASET ******************************************************************************

use "${data_raw}/ssyk2012_4_month_erik.dta", clear
	
	*** GENERATE VARIABLES ***
	
	*ln(ads): Claude drops zeroes, just as I did.
	
	*My old post-ChatGPT variable is defined the same, =1 if >= Dec 2022. 
	rename t_post t_postChatGPT
		*Confirm this:
		tab month_stata if t_postChatGPT==1
		tab t_postChatGPT // All other obs 0, no missing values.

	*Generate post-Riksbanken rate hike dummy
	gen 	t_postRB = 0
	replace t_postRB = 1 if month_stata>=747
		*Double check that it's the correct month number:
		tab month_stata if month_stata==747

	*Fourth quartile of DAIOE-genAI exposure in 2023
	*Extract cutoff value for 75th percentile of genAI exposure (in 2023):
	preserve 
		use "${data_raw}/daioe_panel_ssyk2012.dta", clear	
		keep if year==2023
			sum exp_cumul_genai, d // 75 pctl = 3.270509
	restore
	*Generate the dummy:
	gen 	daioe_genai_q4 = .
	replace daioe_genai_q4 = 0 if ai_daioe_genai< 3.270509 & ai_daioe_genai!=.
	replace daioe_genai_q4 = 1 if ai_daioe_genai>=3.270509 & ai_daioe_genai!=.
		*Check:
		codebook ssyk2012_4 if daioe_genai!=. // 374 occs observed
		codebook ssyk2012_4 if daioe_genai_q4==1 // 93 in Q4
		di 93/374 // 24.9 %. Note that all occupations in SSYK are not necessarily observed in ads.

	*Generate post*exposure interaction terms:
	gen post_gpt_q4 	= t_postChatGPT*daioe_genai_q4
	gen post_rb_q4 		= t_postRB*daioe_genai_q4
		
	
	*** DELIMIT DATASET ***
	*We have already delimited the years to >=2020.
	tab year
		
		
	*** RUN THE REGRESSION ***
	reghdfe ln_ads post_rb_q4 post_gpt_q4, ///
		abs(ssyk2012_4 month_stata) vce(cluster ssyk2012_4)


	*Show that the post-RB coefficient is stable when excluding post-gpt time periods:
	reghdfe ln_ads post_rb_q4 post_gpt_q4 if month_stata<756, abs(ssyk2012_4 month_stata) vce(cluster ssyk2012_4)
	*In other words, when controlling for post-GPT, the post-RB dummy captures May-November 2022.


	
	
log close